### ISSUE TITLE
Script->Celery Idea Feedback

### ISSUE THREAD

**Issue by gpmidi** [Murodese/pynab#35] opened 2014-01-18 19:36 UTC
I'm thinking of trying to move the various scripts so that they are triggered via Celery. This would make running pynab easier as it could all be run from a single Celeryd launch. However those who want a more distributed setup could easily launch more Celeryd wherever. Plus Celery would help by providing cron-based launching and allow the user to more easily control how many of each type of process runs at once. 

http://www.celeryproject.org/

AFAIK the only real downside to this is that there would be a dependency on the Celery library. Since Celery supports a dummy transport (aka memory), it wouldn't require anything external for those that want to keep it simple. 

From what I've seen of the scripts and pynab it doesn't seem like the basics here would be very hard to implement. That said, if you don't think it'd be a good idea, I'd rather find out early on. 

Thoughts?

**Comment by Murodese** [comment] 2015-01-11 03:27
Duplicate of #118.

**Closed by Murodese** 2015-01-11 03:27 UTC
Labels: enhancement
