### ISSUE TITLE
per-user connection limit reached

### ISSUE THREAD

**Issue by qdgtruie** [Murodese/pynab#110] opened 2014-12-31 10:08 UTC
Hi

It seems that either the number of thread connecting to NNTP exceed my provider capacity or something is wrong with the connection pool ...

I get the following 

2014-12-31 06:17:38,400 - ERROR - server: could not connect to news server: 502 Your per-user connection limit reached
2014-12-31 06:17:38,401 - ERROR - server: [alt.binaries.teevee]: nntp error
2014-12-31 06:17:38,401 - ERROR - server: suspected dead nntp connection, restarting
2014-12-31 06:17:43,391 - ERROR - server: could not connect to news server: 502 Your per-user connection limit reached
2014-12-31 06:17:43,392 - ERROR - server: [alt.binaries.teevee]: nntp error
2014-12-31 06:17:43,392 - ERROR - server: suspected dead nntp connection, restarting
2014-12-31 06:17:47,862 - ERROR - server: could not connect to news server: 502 Your per-user connection limit reached
2014-12-31 06:17:47,863 - ERROR - server: [alt.binaries.teevee]: nntp error
2014-12-31 06:17:47,864 - ERROR - server: suspected dead nntp connection, restarting
2014-12-31 06:17:52,108 - ERROR - server: could not connect to news server: 502 Your per-user connection limit reached

Is there a way to configure the max number of connection/thread ?

**Comment by Murodese** [comment] 2015-01-01 02:18
Yeah, this is primarily because it opens a bunch of connections whose sockets then die, so connections can't be closed cleanly. Interested to know why it's happening more often for more people all of a sudden.

**Comment by Murodese** [comment] 2015-01-01 02:41
This should sort itself out once #109 is fixed.

**Comment by qdgtruie** [comment] 2015-01-02 04:48
I just did an update to the last version and now I get ...

2015-01-02 05:47:34,767 - INFO - group: alt.binaries.tvseries: scanning group
2015-01-02 05:47:34,770 - ERROR - server: could not connect to news server: 'module' object has no attribute '_create_stdlib_context'
2015-01-02 05:47:34,771 - ERROR - server: could not send group command: 'NoneType' object has no attribute 'group'
2015-01-02 05:47:34,771 - INFO - group: alt.binaries.tv: scanning group
2015-01-02 05:47:34,807 - ERROR - server: could not connect to news server: 'module' object has no attribute '_create_stdlib_context'
2015-01-02 05:47:34,815 - ERROR - server: could not connect to news server: 'module' object has no attribute '_create_stdlib_context'
2015-01-02 05:47:34,846 - ERROR - server: could not connect to news server: 'module' object has no attribute '_create_stdlib_context'
2015-01-02 05:47:34,847 - ERROR - server: could not send group command: 'NoneType' object has no attribute 'group'
2015-01-02 05:47:34,847 - INFO - group: alt.binaries.hdtv: scanning group
2015-01-02 05:47:34,853 - ERROR - server: could not connect to news server: 'module' object has no attribute '_create_stdlib_context'
2015-01-02 05:47:34,854 - ERROR - server: could not send group command: 'NoneType' object has no attribute 'group'
2015-01-02 05:47:34,854 - INFO - group: alt.binaries.moovee: scanning group
2015-01-02 05:47:34,888 - ERROR - server: could not connect to news server: 'module' object has no attribute '_create_stdlib_context'
2015-01-02 05:47:34,898 - ERROR - server: could not connect to news server: 'module' object has no attribute '_create_stdlib_context'
2015-01-02 05:47:34,924 - ERROR - server: could not connect to news server: 'module' object has no attribute '_create_stdlib_context'
2015-01-02 05:47:34,924 - ERROR - server: could not send group command: 'NoneType' object has no attribute 'group'
2015-01-02 05:47:34,925 - INFO - group: alt.binaries.teevee: scanning group
2015-01-02 05:47:34,934 - ERROR - server: could not connect to news server: 'module' object has no attribute '_create_stdlib_context'
2015-01-02 05:47:34,935 - ERROR - server: could not send group command: 'NoneType' object has no attribute 'group'
2015-01-02 05:47:34,966 - ERROR - server: could not connect to news server: 'module' object has no attribute '_create_stdlib_context'
2015-01-02 05:47:35,008 - ERROR - server: could not connect to news server: 'module' object has no attribute '_create_stdlib_context'
2015-01-02 05:47:35,008 - ERROR - server: could not send group command: 'NoneType' object has no attribute 'group'

**Comment by Murodese** [comment] 2015-01-02 07:05
Which version of python are you using?

**Comment by qdgtruie** [comment] 2015-01-02 08:59
I am using  python3.3

On Fri, Jan 2, 2015 at 8:05 AM, James Meneghello <notifications@github.com>
wrote:

> Which version of python are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Murodese/pynab/issues/110#issuecomment-68511511>.
>



-- 
Y. Saule

**Comment by Murodese** [comment] 2015-01-02 09:13
The SSL changes are 3.4+ only. Are you able to upgrade? Else, you can revert to the previous version of nntplib with `git checkout 058a01a491294d34c0347010386295c55f4e6fb3 lib/nntplib.py`, but it'll possibly cause some problems in the future.

**Comment by qdgtruie** [comment] 2015-01-02 09:18
for now I only revert to no SSL. I will look into upgrading.

**Comment by qdgtruie** [comment] 2015-01-02 09:19
nevertheless I back to the following cycle :+1: 

2015-01-02 10:17:06,192 - ERROR - server: [alt.binaries.teevee]: nntp error
2015-01-02 10:17:06,192 - ERROR - server: suspected dead nntp connection, restarting
2015-01-02 10:17:10,974 - ERROR - server: could not connect to news server: 502 Your per-user connection limit reached
2015-01-02 10:17:10,975 - ERROR - server: [alt.binaries.teevee]: nntp error
2015-01-02 10:17:10,975 - ERROR - server: suspected dead nntp connection, restarting

**Comment by Murodese** [comment] 2015-01-02 09:41
Try rebooting to kill any existing connections. Just to check - are you also using that news server account to download binaries, and are they using up your connection limit?

ie. my account gets 20 connections, I have sabnzbd set to use 10, leaving ~10 for pynab to use.

**Comment by qdgtruie** [comment] 2015-01-02 09:50
I just upgraded to python3.4 and switched back to SSL.

I can restart the container (I am runing pynab in a jail) to see if there
is a change.

My nntp  provider is astraweb and I have 20 connections too.
My sabnzb is setup to use 5 connections, leaving pynab with 15 free to use
...



On Fri, Jan 2, 2015 at 10:41 AM, James Meneghello <notifications@github.com>
wrote:

> Try rebooting to kill any existing connections. Just to check - are you
> also using that news server account to download binaries, and are they
> using up your connection limit?
>
> ie. my account gets 20 connections, I have sabnzbd set to use 10, leaving
> ~10 for pynab to use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Murodese/pynab/issues/110#issuecomment-68516097>.
>



-- 
Y. Saule

**Comment by Murodese** [comment] 2015-01-02 10:23
Latest commit should clear this up, hopefully.

**Comment by qdgtruie** [comment] 2015-01-02 11:58
I updated to the last commit but needed to go back to python3.3 (3.4 is buggy on my box -> keep crashing). therefore I also rolledback the SSL to False.

Following the last commit I get further error : 


2015-01-02 12:52:02,084 - ERROR - server: [alt.binaries.teevee]: nntp error
2015-01-02 12:52:02,084 - ERROR - server: suspected dead nntp connection, restarting
2015-01-02 12:52:02,088 - CRITICAL - Traceback (most recent call last):
  File "/usr/local/www/pynab-postgres/pynab/server.py", line 114, in scan
    status, overviews = self.connection.over((first, last))
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 964, in over
    return resp, _parse_overview(lines, fmt)
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 235, in _parse_overview
    raise NNTPDataError("OVER/XOVER response doesn't include "
lib.nntplib.NNTPDataError: OVER/XOVER response doesn't include names of additional headers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/www/pynab-postgres/pynab/server.py", line 101, in scan
    self.connection.group(group_name)
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 771, in group
    resp = self._shortcmd('GROUP ' + name)
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 611, in _shortcmd
    self._putcmd(line)
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 438, in _putcmd
    self._putline(line)
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 430, in _putline
    self.file.write(line)
AttributeError: 'NNTP' object has no attribute 'file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 1066, in quit
    resp = self._shortcmd('QUIT')
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 611, in _shortcmd
    self._putcmd(line)
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 438, in _putcmd
    self._putline(line)
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 430, in _putline
    self.file.write(line)
AttributeError: 'NNTP' object has no attribute 'file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/www/pynab-postgres/pynab/groups.py", line 78, in scan
    status, parts, messages, missed = server.scan(group_name, first=begin, last=end)
  File "/usr/local/www/pynab-postgres/pynab/server.py", line 121, in scan
    return self.scan(group_name, first, last, message_ranges)
  File "/usr/local/www/pynab-postgres/pynab/server.py", line 119, in scan
    self.connection.quit()
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 1068, in quit
    self._close()
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 1190, in _close
    _NNTPBase._close(self)
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 1059, in _close
    self.file.close()
AttributeError: 'NNTP' object has no attribute 'file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 1066, in quit
    resp = self._shortcmd('QUIT')
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 611, in _shortcmd
    self._putcmd(line)
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 438, in _putcmd
    self._putline(line)
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 430, in _putline
    self.file.write(line)
AttributeError: 'NNTP' object has no attribute 'file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 25, in update
    return pynab.groups.scan(group_name, limit=config.scan.get('group_scan_limit', 2000000))
  File "/usr/local/www/pynab-postgres/pynab/groups.py", line 116, in scan
    return True
  File "/usr/local/www/pynab-postgres/pynab/server.py", line 31, in __exit__
    self.connection.quit()
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 1068, in quit
    self._close()
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 1190, in _close
    _NNTPBase._close(self)
  File "/usr/local/www/pynab-postgres/lib/nntplib.py", line 1059, in _close
    self.file.close()
AttributeError: 'NNTP' object has no attribute 'file'

**Comment by brookesy2** [comment] 2015-01-02 11:59
We should probably merge this issue with https://github.com/Murodese/pynab/issues/109 as they are the same thing.

**Comment by Murodese** [comment] 2015-01-02 14:30
Duplicate of #109.

**Closed by Murodese** 2015-01-02 14:30 UTC
