### ISSUE TITLE
Other TV Release Identification Providers

### ISSUE THREAD

**Issue by NeilBetham** [Murodese/pynab#215] opened 2015-09-23 02:00 UTC
With TVRage looking like it's down for good would it be possible to integrate a different TV release identification API? [OMBD](http://www.omdbapi.com/) now supports TV shows, or `series`. And [TVMaze](http://www.tvmaze.com/api) also has an API for show searching. The latter is looking into adding TVRage IDs to any shows that it can find data for. This would likely also require some modification on the API side of pynab in order to support searching by different ID types. Also I know this won't affect most of the automated down-loaders since they still will likely depend on TVRage IDs but if there is an indexer that supports the new ID set then the down-loaders could follow suit. Truth be told a new API interface for down-loader to indexer communication, other than newznab, needs to be defined. For the moment I've had to shutdown my post processor since it can't identify anything TV related while TVRage is down.

**Comment by gkoh** [comment] 2015-09-23 04:15
> For the moment I've had to shutdown my post processor since it can't identify anything TV related while TVRage is down.

You could just disable the TVRage postprocessing in the config, that's what I've done.

**Comment by NeilBetham** [comment] 2015-09-23 04:29
While yes that is an option for the short term. In the long term another solution will be needed in order to fix the problem. Additionally if you disable it TV Rage post processing then the indexer becomes useless for any sort of TV releases since most searchers depend on the rage id of newznab.

**Comment by Murodese** [comment] 2015-09-23 04:37
I'll investigate this later today. As you said, most of the downloaders rely on the tvr id, so we might have to wait and see what they swap to.

Incidentally, sonarr uses name only, I think.

**Comment by gkoh** [comment] 2015-09-23 04:42
On Tue, 2015-09-22 at 21:29 -0700, Neil Betham wrote:
> While yes that is an option for the short term. In the long term
> another solution will be needed in order to fix the problem.
> Additionally if you disable it TV Rage post processing then the
> indexer becomes useless for any sort of TV releases since most
> searchers depend on the rage id of newznab.

Indeed, I was suggesting it as a short term fix, to allow other
postprocessing to continue.
We will definitely need an alternative if TVRage does not return.

**Comment by NeilBetham** [comment] 2015-09-23 04:58
I did look into sonarr a bit and it looks like they will use a tv rage id if they have one for the show but if they don't then they will do search based on title, season and episode. Relevant [code](https://github.com/Sonarr/Sonarr/blob/master/src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs). Now when they have a rage id and when they don't, i'm still not sure yet.

**Comment by brookesy2** [comment] 2015-09-23 05:19
We can also use thexem.de in the short term. Also can help us translate
elsewhere.

**Comment by Murodese** [comment] 2015-09-23 08:54
Yeah, thexem might work.

**Comment by ukharley** [comment] 2015-09-24 00:04
I've moved on to SickRage (fork of SickBeard) as it doesn't use TVRage anymore (uses tvDB) and searches on title only. Doesn't work for "new releases, as in S01E01" though as the pynab api needs an "episodes" entry in releases/episodes tables. I got around that by tweaking tvrage.py to add them. I wont post the code as Murodese will do a better job of it. As a side note, python 3.4 can't use <import db.regex as regex_data> in util.py. I've commented out all use of it for now as it's only used to import pynab's own regexes, I think. Also been banned from the pre irc channel so be careful how you access it. I'm working on another one.

**Comment by Murodese** [comment] 2015-09-24 04:16
> Doesn't work for "new releases, as in S01E01" though as the pynab api needs an "episodes" entry in releases/episodes tables.

Can you elaborate on that? Episode details should already exist as part of post-proc as per the episode table.

**Comment by brookesy2** [comment] 2015-09-24 04:59
Ukharley, you can use the pre import script in the short term if you still
need em. They are updated once a day usually.

**Comment by Murodese** [comment] 2015-09-24 06:20
Hmm, thexem doesn't let you do show name lookups. Would have to combine tvdb or something with thexem to get tvrage IDs until the downloaders are updated to work with something new. Let me look around and see what the downloaders are doing first, though.

**Comment by ukharley** [comment] 2015-09-24 09:15
@ brookesy2: I am importing them for now but a second choice irc would be worthwhile, for me anyway.
@ Murodese: If there is no rage it doesn't process episodes.

**Comment by brookesy2** [comment] 2015-09-24 19:00
Definitely agreed!! I really need to do more research on requests and how
they work, so we can replicate that ourselves.

**Comment by NeilBetham** [comment] 2015-09-25 01:54
Also if you need help implementing stuff I would be game to contribute where needed.

**Comment by NeilBetham** [comment] 2015-09-30 02:53
TVRage seems to have an [interim](http://www.tvrage.com) page up saying they will be back. So this may resolve it self. Though given the instability of TVRage's platform, and the duration they have been down people may just contribute to another website like TVDB or TVMaze; adding another source for info may still be worth while for post processing. As far as downloaders go It looks like at least Sonarr was planning on falling back to just doing title searches for shows that had no rage id.

**Comment by ukharley** [comment] 2015-09-30 22:44
@brookesy2: Unfortunately, you can't get to the pre irc channels without an invite and key.
I did find one that I've used in my supplimentary prebot script here:
https://gist.github.com/ukharley/f817ce8087778c23d26d
It only gathers pre's for active groups (much more to my liking). If that's not what's wanted comment out the relevant lines in the on_pubmsg function or add a flag in config.py and this script to only process active or all.
For the moment, SickRage is working and being actively developed (in python as well) so I'll be sticking with it, I get an update notification almost every day.

**Comment by brookesy2** [comment] 2015-10-01 05:42
@ukharley Weird. I just restarted my bot and it rejoined and was fine. Mostly irrelevant, as you are right, we definitely need a backup! Thanks for putting some time into it. Total legend :)


2015-10-01 06:40:49 INFO pre: Inserted/Updated - Penn.Zero.Part-Time.Hero.S01E20.720p.HDTV.x264-W4F
2015-10-01 06:40:52 INFO pre: Inserted/Updated - Sick_Of_It_All-Scratch_The_Surface-WEB-1994-ENTiTLED_iNT

**Comment by Murodese** [comment] 2015-10-01 05:54
Sorry, had to rewrite a work project almost entirely so I've been busy as heck for a few weeks. 

The only reason I went with TVR to begin with was SB's insistence on using tvrids as a data source. Sonarr's always fallen back onto title searches, I think.

I'd be totally amenable to modifying the schema so that any kind of metadata can be associated to a release (so each can have a tvr, tvdb, anidb, imdb, whatever ID attached to it). Will require a fairly chunky rework of postprocessing, but a lot of what I've been doing lately has been massive-load distributed processing so I have some new optimisations that I can work into pynab to speed it up quite a lot. I also want to do some more work on better recognition of movie releases, since that seems to be something that pynab's not great at.

@ukharley let me know when the IRC script's done and I'll merge the two (or just submit a PR, either way). From what I saw yesterday it looked pretty good!

**Comment by ukharley** [comment] 2015-10-01 09:35
I think the "nuked" bug is sorted in the backup irc bot. New Gist:
https://gist.github.com/ukharley/13251d904b7cfcac2e59

**Comment by Murodese** [comment] 2015-10-09 06:01
Does this effectively replace the old prebot?

**Comment by ukharley** [comment] 2015-10-09 09:32
I'm using it to replace the existing one as for some reason I was banned from the other, probably restarting the bot too often when no updates were seen. Both bots suffer from a reconnect problem. I think it's down to only having one server in the list. When that one drops it just sits there doing nothing. It's capable of accepting a list [ ] of irc servers it can rotate through but the way it's implemented now it can't. I haven't had time to look any deeper into it.

**Comment by brookesy2** [comment] 2015-10-09 10:42
As @ukharley said, its part connection part server rotate. I have a pretty good connection so it stays online for months sometimes. But a disconnect does hurt :( The library does attempt to re-connect, but sometimes it doesn't work.

Obviously the more the merrier in this instance, redundancy! :)

**Comment by gkoh** [comment] 2015-10-15 01:16
Just noticed that the newznab+ team have committed a change replacing TVRage with TVMaze.

**Comment by Murodese** [comment] 2015-10-15 01:26
Looks good. As I said, I'll replace it with something more generic that supports multiple providers, I just don't have time at the moment (PhD thesis is due in a little over 3 months).

**Comment by brookesy2** [comment] 2015-10-16 09:17
@Murodese I am going to attempt to write this, but it may take longer than you to finish your thesis :) 

Before I start, any preference on what I should use for the json returned. Do you have any library you would use? Or just load it up using standard json libraries from python?

**Comment by Murodese** [comment] 2015-10-16 09:50
Haha, we'll see :) have a look at what I used for the other libraries - I
think it was either simplejson or just the standard python json library?

**Comment by brookesy2** [comment] 2015-10-16 09:57
@Murodese Looks like just standard json library. Will use that for now :)

**Comment by ukharley** [comment] 2015-10-16 10:15
@brookesy, have a look here: https://github.com/srob650/pytvmaze
See if you can adapt that one.

**Comment by brookesy2** [comment] 2015-10-16 10:29
@ukharley This could definitely help, thanks! 

The longest part will be figuring out wtf all this means :)

**Comment by ukharley** [comment] 2015-10-16 10:36
The hardest will be convering existing TVRage and creating new TVMaze db.

**Comment by brookesy2** [comment] 2015-10-16 10:39
@ukharley For now im just going to work on stuffing tvmaze Id's into the old rage box :)

tvmaze does have a lookup based off rageid though. So in cases where things can't be found, we can fall back.

**Comment by brookesy2** [comment] 2015-10-16 10:48
@ukharley python3 support for this isn't looking good :( Sad times.

**Comment by ukharley** [comment] 2015-10-16 10:53
Here's one i was playing with: https://gist.github.com/ukharley/d9ea6146fec8378e644d

**Comment by brookesy2** [comment] 2015-10-16 11:28
@ukharley fortunately the other library was a 2 second fix. Will make a pull request for it later.

https://gist.github.com/brookesy2/d5483f5299d6121e59df

**Comment by brookesy2** [comment] 2015-10-16 14:05
@ukharley This seems to be working, in terms of just the lib.

https://github.com/brookesy2/pynab/blob/development-postgres/lib/tvmazelib.py

Still messing with postprocessing.

**Comment by brookesy2** [comment] 2015-10-16 15:21
Well, I accidentally ran this on my prod db. Will see how that goes....

**Comment by brookesy2** [comment] 2015-10-17 14:08
@Murodese @ukharley So I ran tvmaze across a bunch of releases and its not too bad. We will need to modify the regex that splits out the names though. As the endpoint will NOT return results for things like "Flash 2014". 

It is partly due to the endpoint I used, which is the fuzzy match one. We could use the more expansive one, which returns multiple results, and keep the existing regex. We would then need to do a secondary search. Bit more of a pain, but if you think its preferred I can attempt it!

**Comment by Murodese** [comment] 2015-10-20 08:37
Maybe try it and see how much of a pain it is to determine which of the multiple is the one we want?

**Comment by brookesy2** [comment] 2015-10-20 08:45
@Murodese I think the bigger pain is splitting off the years for things like "Flash 2014" as that wont return any results on any endpoints for tvmaze. Would need to do Flash then search year on the result set.

Here is the example:

http://api.tvmaze.com/search/shows?q=flash

http://api.tvmaze.com/search/shows?q=flash%202014

**Comment by ukharley** [comment] 2015-10-20 11:59
Just had a quick look at the TVMaze forum and they will never add the year or country to the title. That has to pulled from the json data, either/and/or

"premiered":"2014-10-07"
"network":{"id":5,"name":"The CW","country":{"name":"United States","code":"US"

for the Flash example above.

**Comment by brookesy2** [comment] 2015-10-20 12:00
@ukharley Yeah, I found the same :( 

So does this mean we want to use the less restrictive search and match on premiered? We will need to modify the regex to extract show names without dates. How is your regex? :)

**Comment by ukharley** [comment] 2015-10-20 12:06
Sorry, I'm not working on it. Just read your comment and went for a quick gander at their forum. The only free time I have for programing is at weekends and my 65 yr old brain isn't as fast as it used to be so that slows things down as well :)

**Comment by brookesy2** [comment] 2015-10-20 12:12
@ukharley Ha! don't worry about it at all mate. Such is life :) I will do my best, can't promise any speed though!

**Comment by ukharley** [comment] 2015-10-21 10:11
Had a few minutes spare in the office and the best I could come up with is:
(?P<name>.*?)(?<year>19|20\d{2})
Unfortunately, this will only work from 1900 tol 2099 ;)

**Comment by brookesy2** [comment] 2015-10-21 12:41
@ukharley Nice work mate :) I am on holiday next week, if I can find some time I will try bust this out!

**Comment by Murodese** [comment] 2015-10-28 08:14
> @Murodese If you get time, think you can chuck in an alembic for what you are after? tvmaze returns tvrage and thetvdb, so I can build that in to my code. I am not sure which are areas are touched by tvrage ID's though. Does the API get queried by them?

I'll do this over the next couple days. TVRage (and by extension IMDB) IDs are presented as part of the API, which is the only place they get used iirc. I think Sickbeard is the only application to directly query the TVR ID, as well. Sonarr and I think CouchPotato both query by name.

**Comment by Murodese** [comment] 2015-10-28 14:53
Wrote the generic ID table and migration tonight, needs more testing. Also needs tying in with post-processing, obviously. If you want to test the migration (USE A TEST DB, DO NOT RUN ON LIVE DB), it's in the `genericid` branch.

**Comment by brookesy** [comment] 2015-10-28 15:54
Awesome, thanks mate! Will run it on my test DB when I get back from
holidays. Will update tvmaze.py to get all the ID's. Then will have to look
at everywhere else that references it :)

**Comment by Murodese** [comment] 2015-10-28 15:57
I'll do most of that, I have some spare time for a week or so :) I'll let you handle the TVMaze integration, though.

**Comment by brookesy** [comment] 2015-10-28 17:23
Total legend :) hopefully can wrap it up not too long after I get back from
holiday!

**Comment by srob650** [comment] 2015-10-28 17:47
Hi all, I stumbled across this thread and wanted to let you know that my [pytvmaze API](https://github.com/srob650/pytvmaze) now supports fuzzy matching for your above example of "Flash 2014" and others.  Not sure if this helps you out with pynab but if it does feel free to use it :)  For more on how it works scroll down in the README.md to where it says **Search With Qualifiers**.

**Comment by brookesy** [comment] 2015-10-28 18:04
Thanks mate!! I will take a look when I am back from holiday :)

**Comment by srob650** [comment] 2015-10-28 18:13
No problem!  As you mentioned earlier in this thread it does require making multiple calls to TVMaze until it gets a successful result, then it uses the remaining words that were removed from the end of the search as qualifiers to check agianst year, network name, country code, and language.  Even though it makes multiple calls it's pretty fast, since the www.tvmaze.com API itself is quite fast.

I don't generally do as much Python3 testing as Python2 testing so if any 3-specific bugs pop up that I miss feel free to post an issue to the page and I'll happily sort it out :)

**Comment by brookesy2** [comment] 2015-10-28 18:21
Sweet :) currently I just use the broad search (search shows I think?) then
pick the first show with a matching year premier.

**Comment by srob650** [comment] 2015-10-28 18:43
The show search is good but it doesn't return fuzzy results, so in the case of the above "Flash 2014" example it will return nothing.  Also, for situations where there are multiple shows of the same name, things can get tricky.  Take "Utopia" for instance, there are 3 shows all named "Utopia".  Two of them premiered in 2014 so the year alone is not enough.  What my API does is allow you to narrow the search by using "utopia au" or "utopia gb" for country code, or adding multiple qualifiers if you have more information such as "utopia 2014 au abc" (year, country, network).  If you use a qualifier and there are still "tied results" then it will pick the most recent premier date using the whole date, not just the year.

**Comment by brookesy2** [comment] 2015-10-28 19:27
Sounds good, will take a look. Yeah we found out early on about the years
in search. I remove it and search without it. But if it's all in the
pytvmaze lib, that is a win/win :)

**Comment by srob650** [comment] 2015-10-28 20:43
Yeah, it's all there now.  I'm not sure exactly what data you need so obviously you need to do whatever is right for your project, but I'm happy to help out with pytvmaze if your needs fit in with my API's scope :)

**Comment by brookesy2** [comment] 2015-10-29 10:00
@Murodese Unsure if you finished the code for alembic, so if you haven't you can ignore this :)

I get:
```
psycopg2.IntegrityError: update or delete on table "tvshows" violates foreign key constraint "episodes_tvshow_id_fkey" on table "episodes"
DETAIL:  Key (id)=(1) is still referenced from table "episodes".
```
caused by:
```
sqlalchemy.exc.IntegrityError: (IntegrityError) update or delete on table "tvshows" violates foreign key constraint "episodes_tvshow_id_fkey" on table "episodes"
DETAIL:  Key (id)=(1) is still referenced from table "episodes".
 'UPDATE tvshows SET id=%(id)s WHERE tvshows.id = %(id_1)s' {'id_1': 1, 'id': 0}
```

**Comment by Murodese** [comment] 2015-10-30 03:38
Was still going, but that's fine :) Need to drop both FK's and re-add them after. I'll do that tonight.

**Comment by brookesy** [comment] 2015-10-30 09:08
No stress :) Thanks!!

**Comment by Murodese** [comment] 2015-10-31 03:30
Try that :)

**Comment by brookesy2** [comment] 2015-11-01 09:15
@Murodese Sorry for the mammoth delay, 13hr drive back from holiday! Similar error, but we getting closer!

```
psycopg2.IntegrityError: insert or update on table "releases" violates foreign key constraint "releases_tvshow_id_fkey"
DETAIL:  Key (tvshow_id)=(0) is not present in table "tvshows".
```

```
sqlalchemy.exc.IntegrityError: (IntegrityError) insert or update on table "releases" violates foreign key constraint "releases_tvshow_id_fkey"
DETAIL:  Key (tvshow_id)=(0) is not present in table "tvshows".
 'UPDATE releases SET tvshow_id=%(tvshow_id)s WHERE releases.tvshow_id = %(tvshow_id_1)s' {'tvshow_id': 0, 'tvshow_id_1': 1}
```

**Comment by Murodese** [comment] 2015-11-01 14:38
Long drive! I've had to drive 16h or so up to a reef north of us, huge pain. Did it over a couple of days, though.

Try that. I'd test it myself but I don't have any historical test data :(

**Comment by brookesy2** [comment] 2015-11-01 16:43
Ahh nice, you in NSW?

This looks like something I can probably fix up in my db :)

```
psycopg2.IntegrityError: duplicate key value violates unique constraint "tvshows_pkey"
DETAIL:  Key (id)=(1385) already exists.
```

```
sqlalchemy.exc.IntegrityError: (IntegrityError) duplicate key value violates unique constraint "tvshows_pkey"
DETAIL:  Key (id)=(1385) already exists.
 'UPDATE tvshows SET id=%(id)s WHERE tvshows.id = %(id_1)s' {'id': 1385, 'id_1': 1756}
```

**Comment by Murodese** [comment] 2015-11-02 02:14
In Perth, so the drive up to Coral Bay/Exmouth is about that far :)

I think that's an ordering problem - they should be going from 1 upwards, so there shouldn't be any pkey violations. I'll take a look tonight.

**Comment by brookesy2** [comment] 2015-11-02 07:05
@Murodese Ahh nice, im originally from the Sunshine Coast, but I live in Europe now.

Ok sounds good, no stress :)

**Comment by Murodese** [comment] 2015-11-03 08:25
I tested that on some data I have and it seemed to work, let me know how it goes.

**Comment by brookesy2** [comment] 2015-11-03 08:32
Hrmm, no go :( Guessing my db has some anomalies. 

```
psycopg2.IntegrityError: duplicate key value violates unique constraint "tvshows_pkey"
DETAIL:  Key (id)=(1385) already exists.

  File "/media/storage/git/pynab/alembic/versions/3bc50ecd0bb_add_generic_id_support.py", line 62, in upgrade
    bind.execute(tvshows.update().where(tvshows.c.id==show[tvshows.c.id]).values(id=i))


sqlalchemy.exc.IntegrityError: (IntegrityError) duplicate key value violates unique constraint "tvshows_pkey"
DETAIL:  Key (id)=(1385) already exists.
 'UPDATE tvshows SET id=%(id)s WHERE tvshows.id = %(id_1)s' {'id': 1385, 'id_1': 1756}

```

**Comment by Murodese** [comment] 2015-11-03 08:36
Can you paste the rows for ids 1385 and 1756?

**Comment by brookesy2** [comment] 2015-11-03 08:41
It looks like some quality programming:

```
1385	Kendra on Top	 US
1756	The Tall Man	NULL
```

**Comment by Murodese** [comment] 2015-11-03 09:02
Added some debug output, try it again and paste the last few lines :)

**Comment by brookesy2** [comment] 2015-11-03 09:04
Here it is:

```
changing show Cowboy G-Men from 1748 to 1378
changing show The Sandbaggers from 1749 to 1379
changing show Cribb from 1750 to 1380
changing show Tales of the City from 1751 to 1381
changing show The People's Choice from 1752 to 1382
changing show The Tom Ewell Show from 1753 to 1383
changing show Frontier from 1755 to 1384
changing show The Tall Man from 1756 to 1385

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: duplicate key value violates unique constraint "tvshows_pkey"
DETAIL:  Key (id)=(1385) already exists.

sqlalchemy.exc.IntegrityError: (IntegrityError) duplicate key value violates unique constraint "tvshows_pkey"
DETAIL:  Key (id)=(1385) already exists.
 'UPDATE tvshows SET id=%(id)s WHERE tvshows.id = %(id_1)s' {'id_1': 1756, 'id': 1385}

```

**Comment by Murodese** [comment] 2015-11-03 09:05
Can you find the line that is originally 1385? (ie. "from 1385")

**Comment by brookesy2** [comment] 2015-11-03 09:07
Was already looking, can't find one :(

I can gist the whole output if you want.

**Comment by Murodese** [comment] 2015-11-03 09:12
Yeah, thanks.

**Comment by brookesy2** [comment] 2015-11-03 09:14
@Murodese https://gist.github.com/brookesy2/bc8db2edc48279c7291c

**Comment by Murodese** [comment] 2015-11-03 10:37
Bleh. Maybe dump your tvshows table so I can use that data directly? I can't see any obvious reason that it should be doing that.

**Comment by brookesy2** [comment] 2015-11-03 10:39
@Murodese https://gist.github.com/brookesy2/855835dcfda96f694a1d :)

Thanks for spending time on this! I know you are busy!

**Comment by Murodese** [comment] 2015-11-03 11:42
Ugh, ordering didn't commit for whatever reason. Try now.

**Comment by brookesy2** [comment] 2015-11-03 11:47
We appear to be cooking with gas. Its running, will let you know if it fails out :)

**Comment by brookesy2** [comment] 2015-11-03 11:57
Operation, big success! I will work on the tvmaze code hopefully this weekend!

**Comment by Murodese** [comment] 2015-11-03 11:57
Cool. Just have to re-dump new tv/movie/whatever db data for new installs, but I'll do that later.

**Comment by brookesy2** [comment] 2015-11-03 13:08
Err so how does this work? I guess I need to chuck values into dbids, releases, episodes and tvshows? tvshows is now just a join between dbids and the other tables?

**Comment by brookesy2** [comment] 2015-11-03 14:27
@Murodese Whenever you have a spare minute can you check the comments i added here to see if I am on the right track? No rush :)

https://github.com/brookesy2/pynab/commit/04eddf3d769fa3673690b9440f5b8a0f35d0bc89

Legend!!

**Comment by Murodese** [comment] 2015-11-03 14:53
Basically, tvshows/movies are now just tables that hold the name of the show/movie, while the `dbids` table maps the database ID to those entities, e.g (data totally off the top of my head):

```
tvshows.name: Archer

dbids.type: TVRAGE dbids.db_id: 28021
dbids.type: TVMAZE dbids.db_id: 1042
```

In this example, we have one tvshow that's mapped to two different dbs (rage and maze), with their db-specific IDs stored.

**Comment by brookesy2** [comment] 2015-11-03 15:04
@Murodese Yeah, that makes sense. So in the instance of a new tvshow we would add it to tvshow then dbid? As it needs the tvshow_id. Wouldn't we end up with dupe names? or is tvshow_id not unique (it doesn't look it!), so we could just add another db_id, db to the same tvshow_id. Sorry for being dense :)

**Comment by Murodese** [comment] 2015-11-03 15:15
You'd only add a new entry to tvshow if the show doesn't exist yet, otherwise you grab the tvshow_id and use that in your new dbid line. So, for tvmaze postproc it'd be something like this:

1) Get tvshow name and query tvshows for existing show ID
2) Get tvmaze ID from API
3) Add dbids row including tvshow_id and db_id = tvmaze id and db_name = 'TVMAZE'

**Comment by brookesy2** [comment] 2015-11-03 15:16
@Murodese Legend. Thank you. Will progress with that. Kind of what I though, but good to confirm!

**Comment by brookesy2** [comment] 2015-11-05 07:17
@Murodese One thing I noticed is that the sequence on the dbid table doesn't get updated. So I was confused for ages with loads of integrity errors :p

**Comment by Murodese** [comment] 2015-11-05 11:35
Yeah, just one of those things from testing alembic upgrades :)

**Comment by brookesy2** [comment] 2015-11-05 15:04
@Murodese May need your regex skills to strip out countries from searches as tvmaze will fail if its "Bla bla UK".

Otherwise the rest of it is looking good :) Its been a while, so taking me ages!

**Comment by srob650** [comment] 2015-11-05 15:57
@brookesy2 Not sure if you've tried my newer versions of pytvmaze but it actually handles adding qualifiers to the end of a search.  Details are in the readme under the "Search With Qualifiers" header :)

**Comment by brookesy2** [comment] 2015-11-05 15:57
@srob650 Lemme take a look see! Thanks!!

**Comment by srob650** [comment] 2015-11-05 15:59
do a pip install --upgrade pytvmaze and try it out, if it doesn't work for this application I understand but from what I've read here it seems like it should.

**Comment by srob650** [comment] 2015-11-11 18:43
Wanted to chime in here to let you all know that I'm restructuring pytvmaze a bit.  The same functionality will exist for matching parameters however it will require the user to supply known parameters instead of a loose string.  Re-working of the code is not done yet, but when it is, a search with qualifiers will look something like this:
```python
show = pytvmaze.get_show(show_name='utopia', show_year='2013', show_country='au')
```
You will be able to supply as many or few parameters that you have from the options of year, country, network, and language.

**Comment by brookesy2** [comment] 2015-11-11 19:37
@srob650 Bustin my balls here man. Just did a PR! I just, my code needs a ton of reviews before we merge. I will update once you are done :)

**Comment by srob650** [comment] 2015-11-11 20:10
I know I know, sorry!  I feel bad but ultimately I believe it's the right thing to do.  I think sometime in the future (could be a while though) David at TVMaze will give in and handle some fuzzy matching on his end, but until then I think it's best for my api to require specific parameters.  What will change on your end is needing to parse a query before you send it to pytvmaze and find out if it has extra qualifiers in it, and identify them.  There is actually a website that does that pretty well and they have an api, so that could be helpful. http://guessit.readthedocs.org/

Also remember that if the version of pytvmaze that you are using is all you need, you can fork from that commit and continue to use that version in your codebase.

**Comment by srob650** [comment] 2015-11-12 20:33
New version is pushed, and I believe this release to be officially stable as far as current features not changing.

**Comment by brookesy2** [comment] 2015-11-13 09:52
@srob650 Modified my code, could be better, but seems to work :)

**Comment by srob650** [comment] 2015-11-13 14:47
What would make it better for you out of curiosity?

**Comment by srob650** [comment] 2015-11-13 15:40
Ah I see you commented this on your code too, so I'm assuming you mean your work isn't done yet.  I actually have a suggestion, I'll post a comment to the commit

**Comment by Murodese** [comment] 2015-11-26 12:01
Ok, that was a big commit. Pretty sure this should be mostly working now - currently there are two active interfaces (OMDB and TVMAZE since TVRAGE is dead), but more can be easily added. The API should work nicely with either - it retains the legacy api parameters (rid for rage and imdbid for omdb), while bringing in two new api params: dbname and dbid, so you can now search for something by tvmaze id by doing `dbname=tvmaze&dbid=1234`. 

Post-processing has been substantially rewritten to handle this, as has a bunch of other stuff. I'd appreciate some people moving test instances to this branch just to test if it works - I'm going to replicate my own live install and see how the upgrade goes (expecting it to take forever).

**Comment by brookesy2** [comment] 2015-11-26 13:59
@Murodese Awesome work mate! Will have a read and re-clone my instance and give it a whirl too :) Will take all weekend to read through this commit!!

**Comment by srob650** [comment] 2015-11-26 18:40
Heads up, not sure if you guys use the episode info from pytvmaze or not but there will be a minor change in an upcoming commit that will affect you if you do.

Getting Show objects will no longer default to getting episodes at the same time, to improve performance for those who don't need that info.  To get the episodes with the Show object, add the embed to your call like this:
```python
show = pytvmaze.get_show(show_name='dexter', embed='episodes')
```

I will post back here when this is going live, probably will be a day or two but not sure.

**Comment by brookesy2** [comment] 2015-11-26 18:45
@srob650 Bustin our balls man :p I kid, did a quick scan and doesn't look like we are, but murodese will know for sure :)

**Comment by srob650** [comment] 2015-11-26 18:46
Cool deal, if it's true that you aren't then this commit will increase the speed you get your show info from tvmaze :)

**Comment by Murodese** [comment] 2015-11-27 03:27
That works fine - we don't directly use episode info, so any speedup is good :)

**Comment by Murodese** [comment] 2015-11-27 04:39
Running this on my live environment because I'm edgy like that, and seems to all be working fine.

**Comment by brookesy** [comment] 2015-11-27 06:07
Woah. I hope you have good life insurance!!

**Comment by Murodese** [comment] 2015-11-27 07:16
Wouldn't be the first time I've had to rebuild my index from scratch, that's for sure..

**Comment by brookesy2** [comment] 2015-11-27 07:20
I'm making a backup like some kind of sissy loser!

**Comment by brookesy2** [comment] 2015-11-27 08:31
@Murodese I think due to some dodgy checkins by me we managed to overwrite the updated nzedb import script. Want me to make another PR?

**Comment by Murodese** [comment] 2015-11-27 08:33
Double-check that - I did clean up the file somewhat, so it's been changed since you last saw it.

**Comment by brookesy2** [comment] 2015-11-27 08:36
In the tvmaze branch it still references the dropbox download location, which no longer exists :(

https://github.com/Murodese/pynab/blob/tvmaze/scripts/nzedb_pre_import.py

**Comment by Murodese** [comment] 2015-11-27 08:41
Ah, ok. If there's a bit to fix, you can just submit a PR against the `tvmaze` branch - else, toss me the lines to change.

**Comment by brookesy2** [comment] 2015-11-27 08:44
PR is in.

**Comment by Murodese** [comment] 2015-11-27 08:49
Done.

**Comment by srob650** [comment] 2015-11-27 17:57
Heads up, new pytvmaze version with explicit embedding required is live (as discussed above).

**Comment by NeilBetham** [comment] 2015-12-02 06:33
Hi all! Thanks for putting in all the effort to getting this working! I've updated to tvmaze branch and the update went great. However the TVMaze identification doesn't seem to be working for the vast majority of my releases. For reference one of the releases that I think should have been identified but wasn't is `Marvels Jessica Jones`. The post proc debug output showed that it searched for `marvels jessica jones` but then it logged show not found. I performed a search for `marvels jessica jones`, with `show_year` and `show_country` as None, myself using the pytvmaze client and was able to get the correct show. So i'm not quite sure what's going on here. I made sure to update my pip dependencies so should have the latest versions of everything.

**Comment by brookesy2** [comment] 2015-12-02 06:48
@NeilBetham So the code doesn't actually raise an error if the callout fails, it will just say no show found.

https://github.com/Murodese/pynab/blob/tvmaze/pynab/interfaces/tv/tvmaze.py

Lines 39-42. So potentially it may not have been able to hit the tvmaze api. I suppose we could add additional debugging there.

**Comment by NeilBetham** [comment] 2015-12-02 06:51
@brookesy2 I will add some debug to mine locally and see if it's raising any exceptions.

**Comment by NeilBetham** [comment] 2015-12-02 07:05
Okay so I added some debug and in some cases pytvmaze is raising not found exceptions and in some cases its returning a falsy value that causes the not found result. My debug output is the second line

```
2015-12-01 22:59:19 DEBUG  tvmaze: No show found
2015-12-01 22:59:19 DEBUG  showname battle creek, country None, year None
```

And doing a manual search against the TVMaze API yields the correct show.

**Comment by Murodese** [comment] 2015-12-02 07:08
No worries, I'll fix this tonight.

**Comment by brookesy2** [comment] 2015-12-02 07:10
@Murodese When are hero comes alloonnggggg

**Comment by Murodese** [comment] 2015-12-02 14:38
Update and log some of that stuff, not sure what's going on at the moment.

```
>>> pytvmaze.get_show(show_name='battle creek', show_year=None)
<Show(maze_id=734,name=Battle Creek,year=2015,network=CBS)>
>>> pytvmaze.get_show(show_name='battle creek', show_year=None, show_country=None)
<Show(maze_id=734,name=Battle Creek,year=2015,network=CBS)>
>>> pytvmaze.get_show(show_name='marvels jessica jones', show_year=None, show_country=None)
<Show(maze_id=1370,name=Marvel's Jessica Jones,year=2015,network=None)>
```

**Comment by NeilBetham** [comment] 2015-12-03 02:27
Here's some of the debug. This show is legitimately not found on TVMaze and raises an exception as expected.
```
2015-12-02 17:59:07 DEBUG  tvmaze: attempting to find "martha bakes" online
2015-12-02 17:59:08 DEBUG  tvmaze: exception: 'martha%20bakes not found'
2015-12-02 17:59:08 DEBUG  tvmaze: No show found
```

However there are also cases when no exception is thrown but the show is logged as not found.
```
2015-12-02 17:59:09 DEBUG  tvmaze: attempting to find "london spy" online
2015-12-02 17:59:10 DEBUG  tvmaze: No show found
```
```
2015-12-02 17:59:11 DEBUG  tvmaze: attempting to find "expedition unknown" online
2015-12-02 17:59:12 DEBUG  tvmaze: No show found
```

**Comment by srob650** [comment] 2015-12-03 02:30
This should be fixed in the latest release with a new exception ConnectionError.  Let me know if it fixes your problem

**Comment by NeilBetham** [comment] 2015-12-03 02:39
So are the connection errors just TVMaze rate limiting requests?

**Comment by srob650** [comment] 2015-12-03 02:42
I believe so, I haven't actually experienced these errors myself but some users from the FlexGet project have reported what I think is the same issue.  @liiight who works on pytvmaze with me and on FlexGet was only able to reproduce the error on a crappy old netbook, never on good hardware.  The same ConnectionError should get raised if your internet was out or tvmaze was down.

**Comment by NeilBetham** [comment] 2015-12-03 02:45
Yeah, i'm not quite sure what's going either. I'm running off of a Dell PE r410 so i'd be surprised if it's related to hardware.

**Comment by srob650** [comment] 2015-12-03 02:47
Are the requests generated by pynab pretty rapid/numerous?  API throttling is the only thing I can think of currently.

**Comment by NeilBetham** [comment] 2015-12-03 02:58
So I tried running a loop of requests and didn't see any cases where the show wasn't found and no exceptions were raised, so I don't think this is a rate limiting issue.

```
import pytvmaze
while(True):
    [print(pytvmaze.get_show(show_name=name)) for name in ['csi cyber', 'london spy', 'expedition unknown']]

```

**Comment by srob650** [comment] 2015-12-03 03:01
I've tried similar experiments with the same results, so I'm really not sure what's up.  If you every figure out any code that can reproduce the error reliably I'd love to see it.  One user of FlexGet noted that he noticed his ping was oddly high when he was getting errors, so he restarted his router and errors went away.  Pretty hard to track down what that might be

**Comment by Murodese** [comment] 2015-12-03 03:30
Could just be requests getting dropped or the API dropping them, but that should throw the appropriate Python exceptions.

**Comment by NeilBetham** [comment] 2015-12-03 03:30
I've figured out what's going on. When a show has no seasons on TVMaze the __len__ method of the Show class is returning 0. However python uses this to determine truthyness so even though we got a valid result it will evaluated as false.

**Comment by Murodese** [comment] 2015-12-03 03:32
Huh, good catch.

**Comment by NeilBetham** [comment] 2015-12-03 03:33
So whenever a show has no seasons on TVMaze [this](https://github.com/Murodese/pynab/blob/tvmaze/pynab/interfaces/tv/tvmaze.py#L44) will fail.

**Comment by Murodese** [comment] 2015-12-03 03:34
Yeah, as per the Python docs:

> When this method is not defined, __len__() is called, if it is defined, and the object is considered true if its result is nonzero. If a class defines neither __len__() nor __bool__(), all its instances are considered true.

**Comment by srob650** [comment] 2015-12-03 03:43
Aah yes, makes sense.  Embedding episodes into a Show object must be done explicitly with embed='episodes' as of a recent change.  I'll add __bool__ to the Show class.  Thanks for catching this!

**Comment by NeilBetham** [comment] 2015-12-04 02:01
Latest pytvmaze seems to have done the trick! My post processing is working again. Thanks for all the help and hard work everyone!

**Comment by srob650** [comment] 2015-12-04 02:02
Awesome :)

**Comment by Murodese** [comment] 2015-12-04 03:23
Is Sickbeard still using TVRage ID as its primary search qualifier? ;)

**Comment by ukharley** [comment] 2015-12-04 10:30
I stopped using it a few months ago as developement on it has stopped. Just had another look and nothing, it's still using TVRage. I swithced to the SickRage fork back then and it's not bad and is very active with dev.

**Comment by brookesy2** [comment] 2015-12-04 10:34
Sonarr master race nowadays :) Needs mono though.

**Closed** 2016-01-04 08:28 UTC
